# Generated by Django 2.2.6 on 2019-10-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('patient_id', models.BigIntegerField()),
                ('content', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('appointment_title',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('department_name',),
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('disease_name',),
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateTimeField()),
            ],
            options={
                'ordering': ('duration',),
            },
        ),
        migrations.CreateModel(
            name='Prescribtion',
            fields=[
                ('prescribtion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prescribtion_content', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('prescribtion_id',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=50)),
                ('report_center', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('report_title',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Phone', models.CharField(max_length=20)),
                ('current_docID', models.BigIntegerField()),
                ('patient_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('appointments', models.ManyToManyField(to='UMI.Appointment')),
                ('departments', models.ManyToManyField(to='UMI.Department')),
                ('diseases', models.ManyToManyField(to='UMI.Disease')),
                ('doctors', models.ManyToManyField(to='accounts.Doctor')),
                ('durations', models.ManyToManyField(to='UMI.Duration')),
                ('prescribtions', models.ManyToManyField(to='UMI.Prescribtion')),
                ('reports', models.ManyToManyField(to='UMI.Report')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='disease_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMI.Disease'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
