# Generated by Django 2.2.6 on 2019-10-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UMI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='insurance_company',
            fields=[
                ('insurance_company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company_license', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('blood_group', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_license_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
