# Generated by Django 2.2.6 on 2019-10-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UMI', '0003_remove_appointment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='disease_name',
        ),
    ]
