# Generated by Django 2.2.6 on 2019-10-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMI', '0006_auto_20191020_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='duration',
            field=models.CharField(max_length=30),
        ),
    ]
