# Generated by Django 2.2.6 on 2019-10-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191020_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_id',
        ),
    ]
